### PR TITLE
[WIP] Constants in invoke

### LINKED ISSUE #447: Constants not allowed in `invoke` arguments
This control statement:
```
invoke my_add(left = left_r.out, right = 32'd4)();
```
produces the following error message:
```
Error: Calyx Parser:   --> 56:48
   |
56 |       invoke my_add(left = left_r.out, right = 32'd4)();␊
   |                                                ^---
   |
   = expected port
```
We should allow constant literals in invoke arguments.

### PR DESCRIPTION
**Pull request by EclecticGriffin**
Simple fix to close #447. 

Didn't seem that complicated, so I suspect I've overlooked something. I would appreciate it if someone could look this over and point me in the right direction.

If this is somehow correct then there are a few things that should maybe be cleaned up
- [x] Clean up/delete the new example file (since I basically just copied an existing thing) 
- [ ] ? prohibit constant arguments in the output of an invoke ??? (probably best to do in the parser, but could happen in later logic)

### CODE REVIEW

**Comment by rachitnigam** [comment]
Oh, maybe I was wrong! This looks reasonable. Can you add a test for this under `tests/parser/` which will just round trip the example and see if the parser and printer do the right thing?

**Comment by EclecticGriffin** [comment]
Looks like the printer gets it slightly wrong:

```
 54  53│        invoke my_add(
   55  54│          left = y.out,
   56    │-         right = 32'd1
   57    │-         )();
       55│+         right = 32'd1,
       56│+       )();
   58  57│      }
   59  58│    }
```

It adds a comma which will cause the parser to expect another argument

**Comment by EclecticGriffin** [comment]
Ignore the indentation thing, that's my fault

**Comment by EclecticGriffin** [comment]
This should get the printer in agreement with the rest of it

**Comment by rachitnigam** [comment]
Cool, merge it when ready.

**Comment by EclecticGriffin** [comment]
Should I remove the file I added to the examples folder? or leave it there with the appropriate `.expect`?

**Comment by rachitnigam** [comment]
Oh yeah, remove the examples file.

**Comment by EclecticGriffin** [comment]
Done. Looks like some of the tests are failing because they're expecting the old printing with invoke arguments

**Comment by EclecticGriffin** [comment]
Aaand that should hopefully make everything and everyone happy

**Pull request merged**
