### PR TITLE
Add Static Groups to IR 

### PR DESCRIPTION
**Pull request by calebmkim**
(Sorry to have open so many PRs)

@paili0628 and I decided to add a new StaticGroup struct to the IR, which also involved adding a new `StaticEnable` control enum. Right now, it's pretty pointless since Static Groups the exact same thing as regular groups. However, for the next PR, we plan to add the assignment struct generic, which will allow us to more accurately represent static groups in the IR. 

One thing to note: when passes visit enables, we should probably make them visit StaticEnables as well (but that can be for another PR).

### CODE REVIEW

**Comment by rachitnigam** [comment]
Sounds like a plan! One thing to think about is the `for_each_assignment` and `iter_assignment` methods on components which is used by passes assuming that this allows them to iterate over all assignments: https://github.com/cucapra/calyx/blob/master/calyx/src/ir/component.rs#L122-L163

Maybe long term we want this function to return either an `Assignment` and `StaticAssignment` and forcing the callers to separately handle the two cases. Another option is just adding an `assert` that says that there are no static groups in the component

**Comment by sampsyo** [comment]
Awesome!! Looking good.

Here's one extremely tiny question: do we want `StaticGroup` to have a `latency` field? That is, in Calyx 1.0, static-group latency is encoded in an attribute. But of course, that's optional, and latencies are required for any static group. So maybe it should just be represented directly in the IR? (Likely not in this PR; it will take some rearranging to put this data in the right place.)

**Comment by EclecticGriffin** [comment]
+1 to eventually moving the latency into the static group struct! Always better to make it impossible to represent invalid states (like a static group without the latency info)

**Comment by calebmkim** [comment]
Yep, I think we should eventually put a latency field for static groups. 

Eventually, we probably want to deprecate the static attribute totally. However, while we're building up the static groups, we're probably going to keep supporting the static attribute.

**Comment by rachitnigam** [comment]
I agree with @calebmkim that we should deprecate the `@static` attribute completely once we make `static` a keyword.

**Comment by sampsyo** [comment]
Sounds good!!

**Pull request merged**
