### PR TITLE
Some Things to Fix with New TVM Version 

### PR DESCRIPTION
**Pull request by calebmkim**
Not ready for review yet. Just a start

### CODE REVIEW

**Comment by calebmkim** [comment]
@rachitnigam the interpreter tests that involve sequential mems are failing? Is there a way I can disable them for the interpreter?

**Comment by rachitnigam** [comment]
CC @EclecticGriffin?

**Comment by rachitnigam** [comment]
Can you try disabling them from the workflow file under `.github/`? Griffin can re-enable after #1204

**Comment by calebmkim** [comment]
Ok, I disabled the interpreter seq-mem tests. @rachitnigam can you take a look?

**Review by rachitnigam — APPROVED** [review]
LGTM!

**Pull request merged**
