### PR TITLE
[Interpreter] Replace std lib RWLock with parking_lot's version

### PR DESCRIPTION
**Pull request by EclecticGriffin**
A minor PR which replace the `std::sync::RWLock` used by the interpreter config with the version provided by `parking_lot` largely because it takes a different approach to poisoned locks which is more ergonomic for our purposes. It may offer a minor performance boost but that's not really the point. Probably this config stuff should be replaced with use of `Once` but that would require some `unsafe` blocks and I don't think it's worth it right now.

Also added incremental builds to the release profile because it saves me some time when working on things locally. This shouldn't impact build time for the CI since I believe we use the debug profile, but if not we can set the env var `CARGO_INCREMENTAL` to zero. I should note that this means cold release builds will take longer, but hot builds should be faster.

### CODE REVIEW

**Comment by rachitnigam** [comment]
Is the configuration struct accessed in a hot loop somewhere? If so, we should be passing the cloned values/references instead of something that is behind an `RwLock`.

**Comment by EclecticGriffin** [comment]
It's used in a number of places for primitives `execute` and `do_tick` and environment messing. I agree we should probably have the primitives and env functions keep a copy of the relevant config flags. Could potentially pass an Rc of the config through everything, but that would require threading this struct through nearly every call. We could also just have them copy the relevant flags from the rw-config on creation rather than trying to thread it through.

I'm not sure what the best approach is

**Comment by EclecticGriffin** [comment]
Would you be opposed to merging this PR as is for the moment and making an issue for rethinking the general configuration question?

**Comment by rachitnigam** [comment]
Works. Yeah, threading through might not be bad.

**Pull request merged**
