### PR TITLE
[CIRCT] Add Godbolt link for demonstration.

### LINKED ISSUE #1379: [CIRCT] Add Godbolt example to Calyx IR website.
@mikeurbach added Godbolt support for CIRCT. I think it is a great way to demonstrate Calyx, and reproduce bugs. I've constructed a small example of an optimization available in the CIRCT dialect: 

https://godbolt.org/z/c6YW6MT97

It seems that emit-calyx isn't available yet as a command line argument. Perhaps one day we can add support for that as well (unsure what exactly this entails). In any case, thanks Mike! This is super cool work.

### PR DESCRIPTION
**Pull request by cgyurgyik**
Closes #1379.

### CODE REVIEW

**Comment by rachitnigam** [comment]
Looks super cool! Another place to add this link would be the Calyx website under the "CIRCT frontend": https://github.com/cucapra/calyx-site/blob/main/templates/index.html#L22

**Comment by rachitnigam** [comment]
Might be good if we can add the incantation needed to compile the calyx program to `hw` in the example instead of just canonicalization

**Comment by cgyurgyik** [comment]
https://github.com/cucapra/calyx-site/pull/2

Updated with a calyx-to-hw example.

**Comment by rachitnigam** [comment]
Oh, I didn't realize we didn't add the link in the docs at all. @cgyurgyik I think it would also be good to have a link in the CIRCT docs if you'd like!

**Pull request closed without merging**
