### PR TITLE
[Tools] Testing Behaviors of Each Pass

### PR DESCRIPTION
**Pull request by yn224**
This PR attempts to add a shell script that applies each of the defined passes to a given file and tries to find a pattern of interest. This was developed in attempts to understand issue #574.

### CODE REVIEW

**Review by sampsyo — APPROVED** [review]
Awesome; I'm certain this will come in handy in the future.

**Comment by rachitnigam** [comment]
Recommendations

1. Use the [shellcheck](https://www.shellcheck.net/) on the script and fix the errors reported by it.
2. Add the header used in the `flag-compare.sh` script to the top of the file: https://github.com/cucapra/calyx/blob/master/tools/flag-compare.sh#L6
3. Give "$1" and "$2" meaningful names at the start of the file right under the documentation for them and use those names instead of $1.
4. Rename the file to `test-passes.sh` (note the `-` instead of `_`).
5. Add documentation for the script in the debugging tips section of the documentation: https://capra.cs.cornell.edu/docs/calyx/debug/debug.html#reducing-test-files

**Comment by rachitnigam** [comment]
@yn224 this PR is getting stale. What needs to be done to either (1) merge it, or (2) close it?

**Comment by yn224** [comment]
> @yn224 this PR is getting stale. What needs to be done to either (1) merge it, or (2) close it?

Sorry. Since the idea is embedded in PR #625,this PR can be closed.

**Pull request closed without merging**
