### PR TITLE
Fix std_fp_mult_pipe Primitive

### PR DESCRIPTION
**Pull request by andrewb1999**
The current std_fp_mult_pipe primitive is marked as @static(3) in futil and generates correct outputs after 3 cycles, but the done signal is asserted after 4 cycles. This breaks designs that actually use the multiplier in a pipelined way and change inputs every cycle. I fixed this so the done signal is asserted after 3 cycles as expected.

Supersedes #1245

### CODE REVIEW

**Comment by rachitnigam** [comment]
Woah, good catch. However, I'm not sure if this implementation can be used in a pipelined manner. The `start` condition requires that the `done_buf` shift register is empty before a new token can be pushed into the module. This doesn't seem strictly necessary but might be worth fixing if you want to use it in a pipelined way?

**Comment by andrewb1999** [comment]
Seems like this breaks a number of correctness tests. I'll have to look more and see why.

**Comment by andrewb1999** [comment]
> Woah, good catch. However, I'm not sure if this implementation can be used in a pipelined manner. The `start` condition requires that the `done_buf` shift register is empty before a new token can be pushed into the module. This doesn't seem strictly necessary but might be worth fixing if you want to use it in a pipelined way?

Good point, I was wondering about that. I'll take a look at that soon, but for now this change is enough to fix my use case.

**Comment by andrewb1999** [comment]
Ok looks like most of the failures are because designs now take fewer cycles to complete. There's one that fails because of an our of bounds access in verilator, I will look closer.

**Comment by rachitnigam** [comment]
That makes sense. Let me know if you can locally update the tests to take the right number of cycles. And yeah, the OOB access seems super weird?

**Comment by rachitnigam** [comment]
I think https://github.com/cucapra/calyx/issues/1250 is responsible for the failing test

**Comment by rachitnigam** [comment]
Looks like the breaking `@sync` test is fixed by #1251!

**Pull request merged**
