### PR TITLE
Better parsing and help for pass options

### PR DESCRIPTION
**Pull request by rachitnigam**
Fixes https://github.com/cucapra/calyx/issues/1814. Adds new `PassOpt` and `ParseVal` structs to define pass options along with mechanisms to parse more complex command line options.

### CODE REVIEW

**Comment by rachitnigam** [comment]
This also replaces `--list-passes` with the `pass-help` subcommand that can take names of particular passes or aliases

**Comment by sampsyo** [comment]
Extremely cool!! Do you think they should go in the docs anywhere---at least the help commands so people can find the details themselves?

**Comment by rachitnigam** [comment]
Probably under "The Calyx Compiler" but it would be better if we could autogenerate a bunch of information from the driver instead of manually updating the file.

**Comment by sampsyo** [comment]
Indeed—what I meant was to include something brief in the docs, with instructions about how to use the help commands to get an exhaustive listing of the options.

**Pull request merged**
