### PR TITLE
Make TVM-to-Calyx files share components

### PR DESCRIPTION
**Pull request by calebmkim**
Currently, TVM generated Calyx files do not share any components. 

We think this is for two reasons: 

1. Previously Calyx components with ref cells in them could not be shared. However, talking in the Calyx meeting, it seems like almost the exact opposite is true: ref cells, it seems, are never an impediment to sharing. (I've been thinking a bit about it by myself, and I think this is correct. If you think about it, ref-cells have the exact same behavior as passing a bunch of signals to the input/output ports of the component which we know will never be an impediment to sharing. This is because all of the "state" of ref cells are located outside the component they're used in. For example, if we have 2 instances of a component `c1` and `c2` that use ref cells and have a std_mem `mem` that we want to pass as a ref cell, and we invoke `c1[mem]()()` and then later on in the control we are trying to decide whether to invoke `c2[mem]()()` or invoke `c1[mem]()()`. Regardless of whether the second invoke is of `c1` or `c2`, we are still going to have knowledge of the effect that first invoke of `c1` had on the  "internal state" of `mem` when we are doing the second invoke). 
2. Currently, for every operation (even for the exact same operation and exact same memory dimensions), Calyx generates a new component. I think this has to do with the fact that Dahlia generates a new function definition, even for the same operation on a memory with the exact same dimensions. 

I've just added 1). I can work on adding 2) to the current PR as well.

### CODE REVIEW

**Review by rachitnigam — APPROVED** [review]
Looks awesome!!

**Comment by calebmkim** [comment]
An update on getting TVM-to-Calyx code to reuse components. First, I realized that just because two components share the same "root name" (such as conv2d_1x64x55x55) does not mean they will be the same component: the padding and kernel_size parameters could be different, for example. So it seems necessary to have separately defined components in this case. 

However, there is still a decent amount of sharing opportunities in the squeezenet generate file, so  I still have implemented reuse of the Calyx components when possible. Essentially, what I did, is every time we come across TVM IR that is going to be turned into a Dahlia Function (which is in turn transformed into a Calyx component), we ask whether we have already defined the "same" function before (to be considered the "same", you not only need to use the same operation on the same memory widths, but also have the same attributes too): if so, then we just essentially just add another "invoke" of that Dahlia Function/Calyx Component to the control of the program but do not actually define another Dahlia Function as we previously did.

**Comment by rachitnigam** [comment]
Ah, good catch. In this case, we could make the padding of the inputs a part of the name of the kernel as well. So the `conv2d` prefix can have the padding sizes as well. 

> if so, then we just essentially just add another "invoke" of that Dahlia Function/Calyx Component

Does this mean that you don't even generate a new instance and instead just directly share the previously defined instance? It is useful to distinguish between *components* (which are definitions), *instances* (which are sub-components defined in a component), and *invocations* (specific use of an instance).

Either way, it sounds good! If padding is a problem is a hindrance in sharing, we could think of making it a part of the kernel itself, for example, by making it an argument to conv2d.

**Comment by calebmkim** [comment]
Yes, you're understanding correctly. It reuses the instance. So doing it this way you don't actually need the infer share and cell share pass.

**Comment by calebmkim** [comment]
@rachitnigam should I push this or did you want to take another look?

**Pull request merged**
