### PR TITLE
Compress static FSMs

### LINKED ISSUE #929: Static Timing should generate simpler FSM transition logic.
In #909, @rachitnigam [pointed out](https://github.com/cucapra/calyx/pull/909#discussion_r811526931):

> It occurs to me that there might be a simple optimization possible in the realize_schedule method to calculate consecutive "runs" of FSM states where we basically just want fsm.in = fsm.out + 1 and simplify the generated transitions a bit. Not super crucial but will probably start mattering when you look at resources.

This would be neat. Instead of a bunch of conditionals and assigning the next FSM state to a specific number, we could simply increment the FSM state counter. We'd need to identify consecutive "runs" of FSM states where this is valid, and generate different hardware. This should be a non-functional change, but we should be able to measure improved resource utilization post-synthesis.

### PR DESCRIPTION
**Pull request by rachitnigam**
Fixes #929

### CODE REVIEW

**Comment by rachitnigam** [comment]
@mikeurbach just wrote down a small method to compute unconditional runs of static FSM transitions if you want to use this to implement the static FSM compression. Feel free to commit to this branch.

**Comment by mikeurbach** [comment]
Thanks for the head start, I will take a look at building on top of this.

**Comment by rachitnigam** [comment]
Okay, this is ready for review. It manages to compress FSMs when the transitions are unconditional but fails to work in the case when they have a common guard. For example, if there is a long sequence under a conditional branch, this will still generate manual, one-by-one transitions. A future PR can look into compressing other common patterns. Reminder to open an issue marking the two I found:
1. Sequences under `if`
2. When both branches of `if` are balanced

**Review by mikeurbach — APPROVED** [review]
Looks good to me, thanks for finishing the initial implementation off. I will give it a spin on the FSMs I've been looking at, they should be greatly simplified.

**Pull request merged**
