### PR TITLE
Calculate unique IDs for control leaf nodes

### PR DESCRIPTION
**Pull request by rachitnigam**
Adds a new method ir::Component::control_with_node_ids that modifies the
control program to attach `@node_id` which unique number for each enable
and invoke node.

### CODE REVIEW

**Comment by rachitnigam** [comment]
I vaguely remember that @EclecticGriffin had to do something similar for the register unsharing implementation. Maybe we can rewrite things to use this method? Also, does it actually help with what you were trying to do?

**Comment by rachitnigam** [comment]
Relevant issue is #510.

**Comment by EclecticGriffin** [comment]
Right, the issue with the register unsharing was that invoke statements needed a unique label or name so that their uses of variables could be correctly propagated, distinguished, and re-written. The solution at the time was originally using attributes but changed to the more transient raw-pointer based approach to metadata. Given that the pass only needs a unique ID, I think it could be re-written with this, though it wouldn't significantly change the pass's logic. I don't necessarily see a benefit to doing this rewrite beyond general aesthetics, but I'm happy to add it to my task list.

I also think that it doesn't necessarily encompass a general notion of metadata (#510) but thus far we haven't seen a need for this type of metadata emerge so perhaps it's a moot point

**Review by EclecticGriffin — APPROVED** [review]
Code LGTM. Do you think there should there be a method to strip out the annotations as they don't necessarily need to be user facing?

**Comment by rachitnigam** [comment]
Closing this for now. #671 implements this for `tdcc`. We can make it generally available if another pass needs it.

**Pull request closed without merging**
