### PR TITLE
add docs page on undefined parts of the language

### PR DESCRIPTION
**Pull request by rachitnigam**

### CODE REVIEW

**Comment by rachitnigam** [comment]
@sampsyo @EclecticGriffin did I miss something in these?

**Comment by EclecticGriffin** [comment]
LGTM, did we want to include #927 ?

**Comment by rachitnigam** [comment]
Not sure what title it should go under. Any ideas? Something about timing guarantees?

**Comment by EclecticGriffin** [comment]
Seems reasonable to me

**Review by sampsyo — APPROVED** [review]
Sounds great! As for https://github.com/cucapra/calyx/discussions/927, it could even go next to the par discussion… since it also has to do with what is allowed to be shared between concurrently-active groups.

**Pull request merged**
