### PR TITLE
Add GuardCanonical to Validate pass grouping

### PR DESCRIPTION
**Pull request by EclecticGriffin**
Exactly what it says on the tin. We may consider renaming the "validate" grouping to reflect that it does perform some transformations.

### CODE REVIEW

**Comment by EclecticGriffin** [comment]
@rachitnigam can you take a look at the newly failing dahlia test? Should the marked value be going to zero or no?

**Comment by rachitnigam** [comment]
Nope! It’s the value for the computed dot product. Needs debugging.

**Comment by rachitnigam** [comment]
Looks like this also makes some interpreter tests loop forever.

**Comment by EclecticGriffin** [comment]
Huh, you're right. Very strange, I'll do some investigating as well

**Comment by EclecticGriffin** [comment]
Seems like the guard canonicalization pass might have some bugs with lowered code. 

It takes the following 

```
import "primitives/core.futil";
component main<"static"=2>(@go go: 1, @clk clk: 1, @reset reset: 1) -> (@done done: 1) {
  cells {
    reg0 = std_reg(32);
    @generated fsm = std_reg(2);
  }
  wires {
    done = fsm.out == 2'd2 ? 1'd1;
    fsm.clk = clk;
    fsm.in = fsm.out == 2'd2 ? 2'd0;
    fsm.in = fsm.out == 2'd0 & reg0.done & go ? 2'd1;
    fsm.in = fsm.out == 2'd1 & reg0.done & go ? 2'd2;
    fsm.reset = reset;
    fsm.write_en = fsm.out == 2'd0 & reg0.done & go | fsm.out == 2'd1 & reg0.done & go | fsm.out == 2'd2 ? 1'd1;
    reg0.clk = clk;
    reg0.in = !reg0.done & fsm.out == 2'd1 & go ? 32'd400;
    reg0.in = !reg0.done & fsm.out == 2'd0 & go ? 32'd9;
    reg0.write_en = !reg0.done & fsm.out == 2'd0 & go | !reg0.done & fsm.out == 2'd1 & go ? 1'd1;
  }

  control {}
}
```

and produces 

```
import "primitives/core.futil";
component main<"static"=2>(@go go: 1, @clk clk: 1, @reset reset: 1) -> (@done done: 1) {
  cells {
    reg0 = std_reg(32);
    @generated fsm = std_reg(2);
  }
  wires {
    done = fsm.out;
    done = 2'd2;
    fsm.clk = clk;
    fsm.in = fsm.out == 2'd2 ? 2'd0;
    fsm.in = fsm.out == 2'd0 & reg0.done & go ? 2'd1;
    fsm.in = fsm.out == 2'd1 & reg0.done & go ? 2'd2;
    fsm.reset = reset;
    fsm.write_en = fsm.out;
    fsm.write_en = 2'd0;
    fsm.write_en = reg0.done;
    fsm.write_en = go;
    fsm.write_en = fsm.out;
    fsm.write_en = 2'd1;
    fsm.write_en = reg0.done;
    fsm.write_en = go;
    fsm.write_en = fsm.out;
    fsm.write_en = 2'd2;
    reg0.clk = clk;
    reg0.in = !reg0.done & fsm.out == 2'd1 & go ? 32'd400;
    reg0.in = !reg0.done & fsm.out == 2'd0 & go ? 32'd9;
    reg0.write_en = reg0.done;
    reg0.write_en = fsm.out;
    reg0.write_en = 2'd0;
    reg0.write_en = go;
    reg0.write_en = reg0.done;
    reg0.write_en = fsm.out;
    reg0.write_en = 2'd1;
    reg0.write_en = go;
  }

  control {}
}
```

Which the interpreter crashes on due to multiple assignments happening all over the place

**Comment by EclecticGriffin** [comment]
for reference, this is `interp/tests/control/reg_seq.futil`

**Comment by EclecticGriffin** [comment]
Okay, I think I fixed the guard canonicalization pass. Take a look when you have a chance

**Comment by rachitnigam** [comment]
@yn224 please take a look at this change and make sure you understand what was wrong in the original implementation.

**Pull request merged**
