### PR TITLE
[fud] Start some very tiny tests for Xilinx toolchain

### PR DESCRIPTION
**Pull request by sampsyo**
The idea here is to have a quick way to check that everything still works with the (very complex) set of stages that invoke the Xilinx toolchain on Calyx programs. There are two "suites" that share a single test program for now: one that compiles the program, producing an `.xclbin`, and one that both does that _and_ executes the program in emulation mode. Hopefully, this makes it slightly easier to check that we're not breaking anything as we work on this stuff.

A major caveat, of course, is that this is only really meant to run on Havarti; it will is not a CI thing and will not be, barring a huge amount of effort to get Xilinx stuff running in CI.

It is also worth pointing out that the command for emulation is currently very ugly. It should not be necessary to set up the Xilinx tools *before* invoking fud. That's part of the purpose of writing down these tests: to lay bare the fact that work needs to be done here. I'll describe more about what needs to be done in a subsequent issue.

This PR also makes a few changes to the `fpga` execution stage to make the output simpler. It suppresses two forms of logging from the XRT library. Unfortunately, this does not seem to be enough to suppress some logging from the underlying Vitis emulation tool, so I had to `grep` that out for a reasonable/deterministic output. Finally, also moved the running time from the output itself to a proper log message.

Running these things most recently took 5m28s on Havarti, end to end.

---

### [edit] The below problems have been resolved.

Finally, there are a couple of things to fix before this is ready to be useful:

* The compilation output is currently entirely empty. We should capture something about the output, but I'm not sure what (checking in the entire binary executable is probably not right).
* The emulation output contains a bunch of Xilinx logging junk and the execution time, which is nondeterministic. We should strip this out to make the test actually useful as a test.

### CODE REVIEW

**Comment by rachitnigam** [comment]
> barring a huge amount of effort to get Xilinx stuff running in CI

The alternative is to use [self hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners) which might be a good infrastructure investment in the long term. It requires building some server shenanigans but probably not terribly hard.

**Comment by sampsyo** [comment]
Well, unfortunately, that page has a big warning that recommends against using self-hosted runners with open-source repositories...

**Comment by rachitnigam** [comment]
> This is because forks of your repository can potentially run dangerous code on your self-hosted runner machine by creating a pull request that executes the code in a workflow.

It is possible to configure actions to only send payloads when pushed to master or disallow actions from being run entirely when you have PR from a fork. The former would defend against problems in the warning.

**Comment by sampsyo** [comment]
OK, this should finally be ready to be useful! (5.5 minutes at a time…)

**Comment by rachitnigam** [comment]
Is ` tests/xilinx/compile/language-tutorial-iterate.expect` expected to be an empty file? I'd have assumed that it would be an xclbin file.

**Comment by sampsyo** [comment]
Ah yeah, at the moment it is… I haven't actually kept the `.xclbin` checked in because it is binary, enormous (60 MB), and seemingly nondeterministic. I thought about trying to check in the result of some simple sanity check, like `file foo.xclbin`, but even that doesn't know anything about the file (it just says `data`). Then there's `xclbinutil --info -i foo.xclbin`, from Xilinx's own tools, which is very detailed and likely also nondeterministic (contains build dates, etc.). So I'm sort of at a loss about what should be checked in as a result; the compromise here is just to check for failures.

**Comment by rachitnigam** [comment]
Sounds good! LGTM.

**Comment by sampsyo** [comment]
Thanks for taking a look!!

**Pull request merged**
