### PR TITLE
Taylor series approximation of `exp`.

### PR DESCRIPTION
**Pull request by cgyurgyik**
This is a [Taylor series](https://en.wikipedia.org/wiki/Taylor_series#Exponential_function) approximation of `e^x`. It can be dropped into the Relay frontend easily since we can generate the component with the Python AST. It doesn't need a lookup table, so allowing it to work with any width is a bit simpler.

To do this, we split `x` into its integer value and fractional value, `i` and `f` respectively. Then,
1. Compute `e^i` using `fp_pow`.
2. Compute `e^f` using a Taylor Series approximation.
3. Since `e^x = e^(i+f)`, multiply `e^i * e^f`.

**Other**: rename `futil` -> `calyx` for Python AST.

### CODE REVIEW

**Comment by cgyurgyik** [comment]
Update: Accuracy fixed! I accidentally deleted the addition of the first degree (the value `x` itself). Looks good now.

**Comment by cgyurgyik** [comment]
Accuracy dwindles off when as value of `x` increases. My initial guess is because of the bits lost in the `fp_mult_pipe`s. I think I can fix this by instead using the `e^{int_value} * e^{frac_value}` trick.

**Comment by cgyurgyik** [comment]
> Accuracy dwindles off as value of `x` increases. My initial guess is because of the bits lost in the `fp_mult_pipe`s. I think I can fix this by instead using the `e^{int_value} * exp(frac_value)`.

**Comment by cgyurgyik** [comment]
> Accuracy dwindles off as value of `x` increases. My initial guess is because of the bits lost in the `fp_mult_pipe`s. I think I can fix this by instead using the `e^{int_value} * exp(frac_value)`.

This worked.

**Comment by rachitnigam** [comment]
Should we add documentation for this somewhere? Maybe a quick note somewhere in the “tools” section?

**Comment by cgyurgyik** [comment]
> Should we add documentation for this somewhere? Maybe a quick note somewhere in the “tools” section?

Docs added.

**Comment by rachitnigam** [comment]
Cool, merge it!

**Comment by sampsyo** [comment]
Super clever. This is obviously more convenient than generating the lookup table, even if it might come at an overall latency cost for come precisions.

**Comment by cgyurgyik** [comment]
> Super clever. This is obviously more convenient than generating the lookup table, even if it might come at an overall latency cost for come precisions.

Precisely. This isn't exactly a speed demon, but it can easily be dropped into another program with ease and produces a much more accurate result than my first attempt with a table.

**Pull request merged**
