### PR TITLE
Strip suffix in discover external

### PR DESCRIPTION
**Pull request by rachitnigam**
Add the `strip-suffix` flag for the `discover-external` pass. To use:
```
calyx -p validate -p discover-external -p validate -x discover-external:default=16 -x discover-external:strip-suffix=_
```

### CODE REVIEW

**Comment by zzy666666zzy** [comment]
Hi @rachitnigam ,

Thanks for your reply.
I updated and rebuild the project, and used the flag you mentioned. But still no luck. 
The double underscore issue still exists.

Thanks.

**Comment by rachitnigam** [comment]
Can you let me know exactly the command you’re running and maybe provide the input file?

**Comment by zzy666666zzy** [comment]
Hi @rachitnigam 
THe command line I am using is:
```
calyx PATH/gemm4x4_calyx_naive.txt -p validate -p discover-external -p validate -x discover-external:default=16 -x discover-external:strip-suffix=_ -o PATH/gemm4x4_external.txt
```
In the output file you can see
```
    @external @generated ext_mem0_ = std_mem_d1(32, 16, 4);
    @external @generated ext_mem2_ = std_mem_d1(32, 16, 4);
    @external @generated ext_mem1_ = std_mem_d1(32, 16, 4);
```
There is an extra underscore after`ext_mem*`

The input and output files are attached here.
[gemm4x4_calyx_naive.txt](https://github.com/cucapra/calyx/files/11882450/gemm4x4_calyx_naive.txt)
[gemm4x4_external.txt](https://github.com/cucapra/calyx/files/11882452/gemm4x4_external.txt)

Thanks

**Comment by rachitnigam** [comment]
And are you using the version installed from `cargo`? If so, can you run `cargo update calyx`? I think the problem might be an old version of the compiler. The other option to confirm this is to build the compiler from this repository using `git clone ... && cd calyx && cargo build --all`. This will create `target/debug/calyx` which is the latest version of the compiler.

**Comment by zzy666666zzy** [comment]
Oh I know the reason. I updated the repo before, but the calyx binary executable I had been using is in another folder.
It works now. Thanks a lot!

**Pull request merged**
