### PR TITLE
Remove fixed point constant.

### PR DESCRIPTION
**Pull request by cgyurgyik**
Reasoning for removing fixed point constant: the interpretation of the bits should be done by the operator.

### CODE REVIEW

**Comment by cgyurgyik** [comment]
from [dahlia/FutilBackend.scala](https://github.com/cucapra/dahlia/blob/8dd37e4b26878e96b655b23e8abbab8e1581d401/src/main/scala/backends/futil/FutilBackend.scala#L585-L604):

      case ECast(ERational(d), typ) => {
        val _ = rhsInfo
        val (width, Some(int_bit)) = bitsForType(Some(typ), expr.pos)
        val frac_bit = width - int_bit
        val lst = d.split('.')
        val v_1 = lst(0).toInt
        val v_2 = lst(1).toInt
        val fpconst =
          Cell(
            genName("fpconst"),
            Stdlib.fixed_point(width, int_bit, frac_bit, v_1, v_2),
            false
          )
        EmitOutput(
          fpconst.id.port("out"),
          ConstantPort(1, 1),
          List(fpconst),
          Some(0)
        )
      }

I imagine this will be the one place that fp_const is depended upon. We’ll have to instead re-interpret `v_1` and `v_2` accordingly.

**Comment by rachitnigam** [comment]
Presumably you'll be opening a PR in the Dahlia repo to fix the above?

**Comment by cgyurgyik** [comment]
> Presumably you'll be opening a PR in the Dahlia repo to fix the above?

Yes, I won't merge this until the Dahlia PR is ready as well. Just making notes above for later.

**Comment by cgyurgyik** [comment]
Note added in #415 to update the Dahlia frontend and add a test for the fixed point pipes when they are complete.

**Comment by cgyurgyik** [comment]
This PR should fix the (currently) broken build.

**Comment by rachitnigam** [comment]
Looks good!

**Pull request merged**
