### PR TITLE
[xilinx] Logic for parsing AXI memory ports from kernel

### PR DESCRIPTION
**Pull request by yn224**
This PR suggests the method in which AXI ports can be parsed out of generated `kernel.xml` file of the Xilinx tool (relates to PR #888).

### CODE REVIEW

**Comment by sampsyo** [comment]
This has gone green, and I think it's ready to ship! ⛵ ✨

I started with @yn224's XML parsing snippet, made it a little more specific, did some refactoring, and hooked it into the command-line interpolation to correctly invoke the TCL script. I added a second test to the new Xilinx-specific suite: this time the `dot-product` example compiled from Calyx, to demonstrate that we now support compiling programs with more than one external memory. These tests just passed on havarti.

This would check the first currently-unchecked checkbox in #876.

**Comment by rachitnigam** [comment]
@sampsyo does this fix https://github.com/cucapra/calyx/issues/853?

**Comment by sampsyo** [comment]
Ah, yes.

**Comment by rachitnigam** [comment]
Great, thanks for wrapping this up!

**Pull request merged**
