### PR TITLE
serialize to struct rather than string

### PR DESCRIPTION
**Pull request by EclecticGriffin**
Just a minor printing tweak to make the output be a serialized struct rather than strings for the stateful components. This also requires that stateful components implement the serialize method. Otherwise nothing too fancy here and no associated issues.

### CODE REVIEW

**Review by sampsyo — APPROVED** [review]
Woooo, this seems perfect!! It makes the JSON ever closer to being "Verilator compatible." Wahoo!!

**Comment by rachitnigam** [comment]
Looks good!

**Review by rachitnigam — APPROVED** [review]

**Comment by EclecticGriffin** [comment]
@rachitnigam  When you have a sec could you help me out with the CI failures? They seem to be present on master (i.e. I get the same failures when running runt from my local clean copy of master) which is strange since the CI says it's good?

**Comment by rachitnigam** [comment]
Can you make sure to clean rebuild everything? The printer should’ve been updated to print attributes with value = 1 as bare attributes

**Comment by EclecticGriffin** [comment]
Even stranger, the errors I get locally aren't the same as the ones the CI is throwing. Curiouser and curiouser. I'll keep digging

**Pull request closed without merging**
