### PR TITLE
Optimize `ir::Attributes` size

### PR DESCRIPTION
**Pull request by rachitnigam**
The `ir::Attributes` object is currently 72 bytes (according to `std::mem_size`). This PR:
1. Stores known 1-bit attributes in a BitSet inline
2. Moves HashMap for storing other attributes behind a pointer

Attributes are a pretty pervasive data structure so its worth optimizing its size. The representation of the inline set is a bit clunky so might be worth turning it into a proc macro (CC @EclecticGriffin if you have other thoughts)

### CODE REVIEW

**Comment by EclecticGriffin** [comment]
So broadly, it seems like we might benefit from splitting the attributes apart into 3 separate categories.
1. bool attributes (stored in a bit set)
2. numeric attributes (list/set of attribute + number)
3. unknown attributes (map from string -> count) or (association list) 

Then the `Attributes` struct can have the bitset and either pointers for both 2 and 3 or a pointer to a joint structure with 2 + 3 together (basically two more pointers). The former reduces indirection at the cost of space while the latter introduces an extra layer of indirection but makes the actual `Attributes` struct smaller.

For the purposes of the external interface, all the attribute names can be collected under a single module namespace.

Not sure if this is the best way to handle it, but it is one option!

**Comment by rachitnigam** [comment]
Yup, we're on the same page about this but one challenge is making the calls from the methods on `ir::Attributes` convenient. Maybe I can define separate enums for each kind of attribute and then do some clever `From<T>` magic to make this work.

**Comment by rachitnigam** [comment]
Okay, I've taken your suggestion and created separate variants for the different kinds of attributes which makes the code cleaner. Plus added dependency on `strum` which makes the code much cleaner.

**Comment by EclecticGriffin** [comment]
Nice! `strum` seems pretty tidy too

**Comment by EclecticGriffin** [comment]
I guess on a final note and corollary to what I talked about prior: the absolute smallest we can probably get the size is 8 bytes which would be an optional pointer to a data structure with the attributes. This of course pushes the indirection-size tradeoff to its edge and it's unclear whether the performance of this would be worse than allowing some inline. Probably it would be

**Comment by EclecticGriffin** [comment]
Also plus 1 on the `From` magic, that's usually the way to go on these

**Pull request merged**
