### PR TITLE
Add mux primitive

### PR DESCRIPTION
**Pull request by vegaluisjose**

### CODE REVIEW

**Comment by sampsyo** [comment]
Looks straightforward enough! :smiley: I feel silly but I can't really see why CI is still pending… it seems like GH Actions didn't launch any jobs for some reason?

**Comment by vegaluisjose** [comment]
what would be a good way to re-trigger? adding comments?

**Comment by sampsyo** [comment]
I really don't know… I'd normally suggest adding commits, but neither commit above triggered it. I don't see any difference between this and #516, for example, where everything seems to have gone fine.

**Comment by sgpthomas** [comment]
the problem is it's on a forked repo. The checks only run for branches owned by this repo. so one solution is to reopen this on a local branch. Luis, do you have write access to the repo?

This seems silly though, and there's probably a solution to it somewhere. Ill look into it.

**Comment by sgpthomas** [comment]
I think we need something like this in our action definition.
```
on: push: branches: [master, next] pull_request: branches: [master, next]
```

**Comment by sampsyo** [comment]
Ah, right! I think we just fixed something like this in beets:
https://github.com/beetbox/beets/blob/0d624191329f5ef5f9acf40ebd7c46b578383222/.github/workflows/ci.yaml#L2-L8

The reason for hardcoding specific branches is to avoid doubling runs when there's a push to a branch that is also in a PR. Kinda annoying they aren't deduplicated automatically.

**Comment by rachitnigam** [comment]
I'd like to see a use case for the mux primitive because continuous assignments to the same port are muxed by default. For example, you can write:
```
x = cond ? tru;
x = !cond ? fal;
```
Which would generate the assignment:
```
x = cond ? tru
   : !cond ? fal
   : 32'd0;
```

**Comment by rachitnigam** [comment]
With the conversation in #518, I'm more inclined to add this primitive. @vegaluisjose can you add a comment above the primitive to say that this is used for an even more structural representation and should not generally be used in source programs.

Feel free to ping one of us (me, @EclecticGriffin, @sampsyo) once that's done so we can merge it.

**Comment by vegaluisjose** [comment]
Sure thing, I just added the comment `///` but not sure if that is the right way, let me know if there is something that can be done better.

@rachitnigam

**Comment by rachitnigam** [comment]
LGTM!

**Pull request merged**
