### PR TITLE
[fud] Fix return type of `interpret` stage.

### PR DESCRIPTION
**Pull request by cgyurgyik**
After execution, Fud is looking for a SourceType.String, not SourceType.Stream.

### CODE REVIEW

**Comment by cgyurgyik** [comment]
Weird.

```
 fud e examples/futil/memory-by-reference/memory-by-reference.futil  \
--to interpreter-out -s interpreter.data examples/futil/memory-by-reference/memory-by-reference.futil.data \
-pr -csv
```

leads to:

```
Traceback (most recent call last):
  File "/opt/anaconda3/bin/fud", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.8/site-packages/fud/main.py", line 289, in main
    exec.run_fud(args, cfg)
  File "/opt/anaconda3/lib/python3.8/site-packages/fud/exec.py", line 172, in run_fud
    print(data.convert_to(SourceType.String).data)
  File "/opt/anaconda3/lib/python3.8/site-packages/fud/stages/__init__.py", line 103, in convert_to
    data = Source.convert_map[self.typ][other](self.data)
  File "/opt/anaconda3/lib/python3.8/site-packages/fud/stages/__init__.py", line 61, in <lambda>
    SourceType.String: lambda s: conv.bytes_to_string(conv.stream_to_bytes(s)),
  File "/opt/anaconda3/lib/python3.8/site-packages/fud/utils.py", line 105, in stream_to_bytes
    return data.read()
AttributeError: 'str' object has no attribute 'read'
```

Not even sure why that fixes it. I thought type annotations were meaningless in Python. In any case, it breaks the case when no `-pr` flag is used.

**Comment by rachitnigam** [comment]
The type annotations are used by the `@step` decorator to generate code to connect inputs and outputs of consecutive steps. The `Stream` type means that the data will be generated on an output stream and can be redirected into as input to another stage that expects `Stream`.

**Comment by cgyurgyik** [comment]
I need to fix this still.  It sure what the best way is.

**Comment by cgyurgyik** [comment]
Not

**Comment by EclecticGriffin** [comment]
Why is it a problem at the output is a stream?

**Comment by rachitnigam** [comment]
Is this getting in the way of collecting data for the paper, if so, I can look into it. Otherwise, de-prioritize this.

**Comment by cgyurgyik** [comment]
The profiling for interpreter won't work without the single line change here. But this obviously breaks where the interpreter expects a Stream. I think changes will be required in exec.py to check for different output types instead of assuming it's a SourceType.String.

**Comment by EclecticGriffin** [comment]
Another possibly silly question, does changing the Sourcetype to String break anything?

**Comment by cgyurgyik** [comment]
Yes, see the Rust Interpreter tests for Github Actions. Unless you're saying changing it elsewhere.

**Comment by EclecticGriffin** [comment]
Okay, maybe I am being exceedingly silly but it seems like the problem is that profiling uses the data field which is used by the rest of fud and so has the type of the last output, except the profiling changes the internal data to a string.

Seems like you want to add
```
data.typ = SourceType.String
```

or just use a separate variable?

**Comment by EclecticGriffin** [comment]
See if the thing I just committed resolves the problems

**Comment by cgyurgyik** [comment]
Nice, simple fix. Merging.

**Pull request merged**
