### PR TITLE
The .expect files for tests

### PR DESCRIPTION
**Pull request by almathaler**
These are .expect files for tests that worked before we began revamping the interpreter. These tests will serve as our baseline tests once we get the interpreter functioning again.

### CODE REVIEW

**Comment by almathaler** [comment]
Might have made this pull request wrong but all that needs to be added to master are the .expect files. Everything else can be ignored (the other files are out of date)

**Review by EclecticGriffin — APPROVED** [review]
I took a quick look over things and it all seems good! Obvs we'll want to fill in the `clk` wire later (or remove it) once things are actually running, but it's very good that we have this suite to work with. 

Merge when you're ready

**Comment by rachitnigam** [comment]
Long term, the interpreter should start running the tests under `tests/correctness` to test for verilator equivalence.

**Comment by rachitnigam** [comment]
Also, should this have a `runt.toml` file too and be automatically run from in the CI workflow?

**Comment by EclecticGriffin** [comment]
There is already a `runt.toml` file added in #519. We should eventually add the tests to the CI and correctness groupings, but let's hold off on that for the moment since they won't work yet

**Pull request merged**
