### PR TITLE
Compile-invoke compiles `ref` cells as well

### PR DESCRIPTION
**Pull request by rachitnigam**
Fixes https://github.com/cucapra/calyx/issues/1649.

### CODE REVIEW

**Comment by rachitnigam** [comment]
@EclecticGriffin this change gets rid of the `compile-ref` pass and merges the logic with `compile-invoke`. Unfortunately, this means that if we run `compile-invoke` for every program that has a `ref` cell, the interpreter will never see an `invoke` statements. Just wanted to get a sense of how useful explicit `invoke` statements are for the interpreter.

**Comment by rachitnigam** [comment]
Okay! So we can default to running `compile-invoke` before any test and that should be good.

**Comment by EclecticGriffin** [comment]
Yeah that should work just fine! If it doesn't then that means there are bugs for me to sort out 😓

**Comment by rachitnigam** [comment]
Hm, actually, looks like there is a bug in the interpreter for that test. I get:
```
 thread 'main' panicked at 'Component interpreter reset before finishing', interp/src/interpreter/component_interpreter.rs:424:13
 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Pull request merged**
