### PR TITLE
SDN correctness

### PR DESCRIPTION
**Pull request by anshumanmohan**
This is not necessarily something to merge, but just a place to surface something interesting and stare at it together. I have made three sibling directories:

```
static/
|-- sdn_static.data 
|-- .expect
|-- .futil 
|-- .py

promote/
|--- sdn_promote.data
|-- .expect
|-- .futil   

no-promote/
|-- sdn_no-promote.data 
|-- .expect 
|-- .futil

sdn.py
```

Where:
1. All the .data files are the same.
2. All the .expect files are the same.
3. The `promote` and `no_promote` .futil files were generated using `sdn.py`, which generates straight Calyx. Those two are identical.
4. The `static` .futil file was generated using `sdn_static.py`, which generates Piezo. Really it just calls `sdn.py` with a `static=True` parameter.

The difference is in how we run all these tests with `runt`.
1. The static stuff takes `-s calyx.flags "-d well-formed"`.
2. The promote stuff takes no Calyx flag.
3. The no-promote stuff takes `-s calyx.flags "-d static-promotion"`.

All these tests run correctly (`runt -i 'sdn' -d`).

Is this compelling? Can we assert correctness? Am I missing something?

### CODE REVIEW

**Comment by sampsyo** [comment]
This is an interesting prospect; thanks for showing it off!

I see the wins for the "regularity" in the testing setup. On the other hand, I think there are two important trade-offs here:

* The generator itself is no longer tested automatically. That is, the old version "trusted" the Python generator program as the source of truth. The new version requires a human to manually generate Calyx source programs. So runs in CI, for example, can no longer catch when a person forgot to do this (and when the Python generator code breaks).
* It requires duplicating the input & output files (`.data` & `.expect`) for each configuration. This will make diffs larger, and it will scale with the number of options to the generator.

Broadly, I guess it is worthwhile to point out here that differential testing (which is what we want here) is sometimes an uncomfortable fit for snapshot testing frameworks (which is what Runt wants to provide). That discomfort is addressable, but it's worth thinking beyond Runt sometimes… i.e., thinking through which features we might want to add to Runt to make differential testing easier/simpler, or thinking about whether Runt is actually the right tool for the job.

**Comment by anshumanmohan** [comment]
Thanks for taking a look! Yes agreed, those are both sources of clunkiness. I think there is a fix in each case, though! 
- I can bring the .py generator back into play as the source of truth. There will be only one generator, `sdn.py`, which will typically generate Calyx .futil but will have a command-line argument `--static` to generate a Piezo .futil instead. With this in place, we'll need three (now four) different `runt` stanzas, each of which captures only `sdn.py`, but runs a different command on the same file.

    1. ` -s calyx.flags ' -d static-promotion '`, to test Calyx without promotion.
    2. No flags, to test Calyx with promotion.
    3. Pass `--static` with the Python command, and then `-s calyx.flags ' -d well-formed -d static-promotion '`, to test Piezo without promotion.
    4. Pass `--static` with the Python command, and then `-s calyx.flags ' -d well-formed '`, to test Piezo with promotion.

- I think the duplicated .data and .expect issue can be resolved using `runt`'s `expect_dir` feature? I didn't have time to investigate fully.

A reasonable counter to all this is that I've sorta shifted the problem over to the `runt.toml` file. It seems to me like it wants to capture globs and run them the same way, not capture individual files and run them different ways.

**Comment by rachitnigam** [comment]
@anshumanmohan anything blocking the merge of this issue?

**Comment by anshumanmohan** [comment]
It probably should not be merged as-is for the reasons that @sampsyo has outlined. If my proposal for tidying sounds okay, I could do that tidying (probably in a baby PR that branches out of and into this one), and then we could merge this one.

**Pull request merged**
