### PR TITLE
Switch connect order

### PR DESCRIPTION
**Pull request by susan-garry**
For readability, `Connect(dest, src)` now outputs `dest = src`. Previously, the order was switched, so `Connect(src, dest)` became `dest = src`.

### CODE REVIEW

**Comment by rachitnigam** [comment]
Looks like there are a couple of test failures. All the frontends that use this: systolic, NTT, MrXL, need to be fixed before this can be merged

**Comment by susan-garry** [comment]
It looks like all of the frontends have been successfully updated!

**Review by rachitnigam — APPROVED** [review]
Looks good to me!

**Review by sampsyo — APPROVED** [review]
Heck yes!! Nice work tracking down all these uses of the API. :rocket:

**Pull request merged**
