### PR TITLE
Split Calyx into various crates

### PR DESCRIPTION
**Pull request by rachitnigam**
Some questions:
- Why does `interp` depend on `calyx_frontend` and `calyx_opt`? Can we remove the dependency and rely on `fud` to execute Calyx passes for the interpreter?
- Similarly, lots of tools need to rely on `calyx_frontend`. Maybe some way to change that (time for a bitcode!!)

## TODO
- [x] Build the docs website correctly
- [x] Make `cargo run -- <file>` work again
- [ ] Fix links in the documentation that point to the source code docs (Add a new pass from #1394)

### CODE REVIEW

**Comment by priyasrikumar** [comment]
Looks super useful! Was just wondering if you had an idea of how you were going to split things up/what is going to go where? I see a `calyx_utils` crate but want to make sure I have the full picture!

**Comment by rachitnigam** [comment]
@priyasrikumar first pass on splitting up was trying to keep folders in `calyx/src/` together while keeping a DAG dependency graph. The most unintuitive thing currently split up is putting some `ir` structures like `Primitive` in `frontend` because we never change their representation.

**Comment by rachitnigam** [comment]
Not clear why we should have `traversal` stuff in the IR instead of the passes package (`calyx-opt`)

**Comment by rachitnigam** [comment]
Okay, this has a couple of potentially controversial choices:
1. Some IR-related data structures like `Primitive` and `Port` live inside `frontend`. This is because their representation is not changed during the frontend -> IR conversion. The downside is that it makes the frontend and the parser a hard dependency for the IR which might not be desirable
2. Disables the building of source-code documentation. AFAIK, we never really used it to any large extent but it might be worth recreating for the Calyx tutorial

@EclecticGriffin @sampsyo @priyasrikumar @anshumanmohan thoughts?

**Comment by sampsyo** [comment]
Super cool; a big crate split like this seems like it will make a few things much easier.

About the "reverse dependency" on the frontend: makes sense to me! Probably an extremely naive question: any particular reason why these shouldn't go in the IR crates instead? The frontend could just have a type alias that says "my `Port` is the same as the IR's `Port`" or something. But truly, if this is the way things currently are, that decoupling could come in a future step, and obviously isn't a big deal immediately because we have the luxury of being in a monorepo.

Maybe in the future, we would want source code documentation back for only the IR crate. Not sure.

**Comment by rachitnigam** [comment]
Yeah, a weird dependency issue is that the AST to IR conversion needs access to IR internals that shouldn't be generally exposed and is therefore in the IR crate. However, this creates a AST -> IR dependency so we can't move the structures in IR because that would create an IR -> AST dependency

**Comment by rachitnigam** [comment]
Also we're running into a failure because `cargo run` can no longer find the `futil` binary is probably not building it correctly

**Comment by sampsyo** [comment]
Got it; thanks for explaining!

That makes it seem to me that the long-term decoupling solution is:
* Move AST-to-IR transformation to the frontend crate.
* Create an appropriately public API for constructing IR that suffixes to enable the above.
* Move `Primitive` & `Port` to the IR crate, and either use them directly from the AST crate or conjure carbon copies of them in the AST crate.

Needless to say, that's definitely future work not for this PR…

**Comment by rachitnigam** [comment]
All right, this beast is ready to be merged. We'll need to fix some links here and there but it should be fine

**Comment by EclecticGriffin** [comment]
Incidentally, love the branch name!

**Pull request merged**
