### PR TITLE
Builder: perform op and store in reg

### PR DESCRIPTION
**Pull request by anshumanmohan**
I began to notice a little pattern in the builder, so I lifted it using a helper. The observation is that we frequently want to perform some operation and immediately store the answer in a register.

### CODE REVIEW

**Comment by rachitnigam** [comment]
Interesting! It occurs to me that we might be able to describe this in some sort of unified interface for the `op_use` methods as well: if you give the method a register, it's going to construct a group and store it in the register. Otherwise, it generates a `CellGroupBuilder`.

**Comment by rachitnigam** [comment]
Although that might feel a little *too dynamic*.

**Comment by anshumanmohan** [comment]
A little too dynamic for my taste, to be sure, but I'd defer to yall for design decisions such as this!

**Comment by rachitnigam** [comment]
Just a thought! And yeah, I agree its too dynamic. Since you're working on this most actively, I think your opinion reigns supreme!

**Pull request merged**
