### PR TITLE
Librarize fud

### PR DESCRIPTION
**Pull request by rachitnigam**
Start work towards librarizing fud. The idea is long-term, we should be able to write python scripts that call `fud` as a library and perform actions for us. Couple of useful scripts:
1. Compute resources for many files (#1416)
2. Computing the frequency max for a design which requires running the synthesis and then changing the constraint file which I currently do by hand

### CODE REVIEW

**Comment by EclecticGriffin** [comment]
Just gonna throw out an idea that we might wanna cache certain file translations? Like turning a data file into the appropriate folder/encoding since that is translation time we could ameliorate for successive runs

**Comment by sampsyo** [comment]
Nice; looks great! It seems like one nontrivial feature that might be useful for some of this stuff (like collecting synthesis results) could be to return the output as a string (instead of printing to stdout)?

**Comment by calebmkim** [comment]
I'm trying to get started on #1416 and I'm about to push some (small) changes to this PR that would help get it along. 

As I've gotten started, I've had a couple of questions related to this PR
1) When working on the python script for #1416, I've just been importing the functions that I might need from `fud` (e.g., `from fud.stages import SourceType` in the python script). Is this fine, or is there  a better way to do things? and relatedly
2) What is the work left needed to merge this PR? I have a slight preference to merge this sooner rather than later only bc I want to get an early/simple version of #1416 started (although it's obviously not too urgent).

**Comment by calebmkim** [comment]
Ok, I added a `get_fud_output` that returns an `output` in the form of a `Source`.  Scripts can now call `get_fud_output` to get the output in a `Source` form instead of printed in `stdout`. 

(`run_fud` also now calls `get_fud_output` (which does most of the work) before handling the `output` appropriately)

**Pull request merged**
