### PR TITLE
Integrate testing for interpreter

### PR DESCRIPTION
**Pull request by rachitnigam**
Make the following test suites run on CI for the interpreter:
- [x] `cargo test` from the `interp` directory
- [x] `runt` from the `interp` directory
  - This will require skipping the currently failing tests. This can be done by renaming the `.expect` file to `.skip`.

## TODO
- [x] Fix the `cargo test` tests.

### CODE REVIEW

**Comment by rachitnigam** [comment]
`cargo test` in the `interp` directory currently fails for:
```
failures:
    test::prim_test::test_mem_d1_imval
    test::prim_test::test_mem_d1_tlv
    test::prim_test::test_mem_d2_imval
    test::prim_test::test_mem_d2_tlv
    test::prim_test::test_mem_d3_imval
    test::prim_test::test_mem_d3_tlv
    test::prim_test::test_mem_d4_imval
    test::prim_test::test_mem_d4_tlv
    test::prim_test::test_std_reg_imval
    test::prim_test::test_std_reg_tlv
```

Maybe one of @EclecticGriffin @ai-cu @almathaler @yn224 can take a look and fix it?

**Comment by rachitnigam** [comment]
The CI integration is done. All that needs to be done is fixing the cargo tests. I've also turned the failing `runt` tests to be skipped. @EclecticGriffin feel free to override me if this was the wrong decision.

**Comment by EclecticGriffin** [comment]
Oops sorry, the failed tests are my fault. I forgot to fix them when I introduced pulse values

**Comment by EclecticGriffin** [comment]
Okay the tests both unit and doc should be fixed now! They even pointed me toward a tiny bug that I had missed

**Comment by EclecticGriffin** [comment]
And the `.skip` files for the failing runt tests seems like a good way to go, so no objections from me

**Pull request merged**
