### PR TITLE
Update to Dahlia means we Change some of the .expect files

### PR DESCRIPTION
**Pull request by calebmkim**
Now all of the Dahlia frontend tests map to 1d sequential memories.

### CODE REVIEW

**Comment by calebmkim** [comment]
So some of the relay tests are failing, but since my local computer has a new version of TVM so I can't override the tests. 
Is there a way to get back to switch between the 2 different versions of TVM without having to build each time?

**Comment by rachitnigam** [comment]
Not that I know off unfortunately

**Comment by rachitnigam** [comment]
You could try using the docker image!

**Comment by rachitnigam** [comment]
So I tried updating the tests and a problem is that the correctness tests fail because the TVM input provides `std_mem_d1` to the kernels when they expect `seq_mem_d1`. The fix would require TVM frontend to generate `seq_mem_d1` instead of `std_mem_d1` everywhere. This is making me think that we should just do the transition all in one go.

**Comment by calebmkim** [comment]
I see. 
I'm working on trying to update TVM now and it doesn't look like as much work as I thought.
So it seems like maybe I should try to update the TVM version as well in this PR? (That seems fine to me, but we would also probably want to update the Calyx documentation that talks about TVM)

**Comment by rachitnigam** [comment]
Okay, take a shot!

**Comment by calebmkim** [comment]
Sorry, where would I go to change that? Is this in [.github](https://github.com/cucapra/calyx/tree/master/.github)/[workflows](https://github.com/cucapra/calyx/tree/master/.github/workflows)/integration.yml ?

**Comment by rachitnigam** [comment]
You'll need to update this file to invalidate the caching step in the workflow file: https://github.com/cucapra/calyx/blob/master/versions/tvm

**Comment by calebmkim** [comment]
@EclecticGriffin do you know how to change the workflow files so that that for our tests, we use the updated version of TVM (v0.10.dev0) that we selected at last week's meeting?

**Comment by EclecticGriffin** [comment]
Perhaps you need the specific commit hash? 

`0e23122846aa3b7a5350102d8c06fa21695d34be`

**Comment by EclecticGriffin** [comment]
Oh wait, it's trying to do the topi install but topi lives inside tvm in the newer repo, that's the problem

**Comment by EclecticGriffin** [comment]
You want to fix the two lines here: https://github.com/cucapra/calyx/blob/master/.github/workflows/rust.yml#L214

**Comment by calebmkim** [comment]
Sorry if this is a dumb question, but: it seems like the topi folder that lives inside tvm doesn't have a file names `setup.py`. What should I do about this? In other words, what should I run to get topi installed with this newer version?

**Comment by EclecticGriffin** [comment]
No separate install step for topi is needed since it's now a submodule in the tvm library. The lines related to it can be removed

**Comment by rachitnigam** [comment]
Can you also update the Dockerfile for the TVM build: https://github.com/cucapra/calyx/blob/master/Dockerfile

**Comment by calebmkim** [comment]
Updated the docker file

**Comment by rachitnigam** [comment]
LGTM!

**Pull request merged**
