### PR TITLE
Tracing Infrastructure

### PR DESCRIPTION
**Pull request by rachitnigam**
Adds the `tracing` crate so that passes can send tracing information. The frontend subscribes to these using a stderr printer.

### CODE REVIEW

**Comment by sampsyo** [comment]
Sounds cool overall! I took a look at the [tracing crate](https://crates.io/crates/tracing), and at a very cursory glance I couldn't quite grok the primary difference they are getting at between tracing and plain old logging. It seems like their chief concern is tracking causality among async tasks, right? But I'm not sure that applies to us—maybe a brief summary here of the high-level idea would be helpful, for posterity if nothing else?

**Comment by rachitnigam** [comment]
Mostly used it because I read this blog post: https://fasterthanli.me/articles/request-coalescing-in-async-rust

I think `log` just provides the functionality of emitting events and other crates can subscribe and print the events. You're probably right about just using `log` because we don't care about async stuff

**Comment by rachitnigam** [comment]
Switched this PR to use `log` instead of tracing. The log outputs still have colored output so I'm happy!

**Comment by sampsyo** [comment]
Wahoo; awesome!

**Pull request merged**
